### ISSUE TITLE
Refactor package names and structure

### ISSUE THREAD

**Issue by livthomas** [dhis2msg/DHISmessenger#4]
First of all, package names in Java should be written in all lower case to avoid conflict with the names of classes or interfaces. Then some really long names such as `Google.CloudMessaging` should be shortened to just `gcm` or similar. And I would also suggest renaming the basic package from `org.dhis2.messaging` to `org.dhis2.messenger` since the former can be mistaken for server side messaging which is not completely true in this case. However, the most important thing is the structure. It's a mess right now. We should clearly distinguish GUI and service classes and put them into different packages. And I think service classes should be divided into two main packages `rest` and `xmpp` with classes used by both of them in some other package. What do you think? Do you have any suggestions? Let's discuss it a little bit before making any changes.

**Comment by livthomas** [comment]
I would suggest the following package structure:
- org.dhis2.messenger
  - core
    - gcm
    - rest
      - async
        - callback
    - xmpp
      - listener
  - gui
    - activity
    - fragment
    - view
  - model
    - adapter

@vladgalf you have a good overview of the whole application. What do you think about this package structure?

**Comment by VladislavAlfredov** [comment]
Looks interesting :)
A few points to consider are:
- The rest client is spread out. So you will find a lot of code in the (rest) Activities and Fragments that are essentially high level rest client begaviour enclosed in anonymous AsyncTasks classes atm. So that might remain a bit of an issue. And I am not sure if moving them from the anonymus classes to separate ones is worth the efford given the little time that we have. Might be better off as a stretch goal instead.
- Since gcm is to be used only for notifications, that might qualify it as "utils", "common" or something along these lines. I think that common is a better name, because you could naturally put interfaces for callbacks there for example...etc
- I noticed that XMPPDataChanged interface  and RESTDataChanged are identical, just with a different name... So it might be worth merging these two into DataChangesListener (or something along these lines). And putting it in common instead. Also further such refactoring could be a stretch goal.
- org.dhis2.messenger
  - common
    - -interfaces wihtout package name and other shared code-
    - gcm
  - rest
    - async
      - callback
  - xmpp
    - listener
  - gui
    - activity
    - fragment
    - view
  - model
    - adapter

For reference here is what I roughly considered last week:
It was inspired by the fact that there are two clients/sub-apps in one app.
But your suggestion seems more sane tbh as this will make less drastic changes.
- org.dhis2.messenger.
  - gcm
  - xmpp
    - gui
    - data
    - async
    - activity
    - fragment
    - view
    - model
  - rest
    - gui
    - data
    - async
    - activity
    - fragment
    - view
    - model
  - common
    - gui
    - data
    - async
    - activity
    - fragment
    - view
    - model

To be honest though at the moment I kind of have my hands full with the caching, as it is going kind of slower than I expected. So I don't know if I can help much with the restructuring process.

**Comment by livthomas** [comment]
I don't want to change anything inside the classes. All I want to do is organize them into different packages than now. That's why I think it's worth splitting them into `core` and `gui` packages so you can easily see what is a class used for. After this issue is resolved, we can think about moving some parts of the classes in `gui` package which should not be there to `core` package. And of course there are some common classes for both XMPP and REST but it doesn't really matter. They can be placed either directly to `core` package or to `common` package as you suggested. When it comes to GCM I think it should be in a separate package since it is the third way how our application communicates with outside world (besides REST and XMPP). Does it make sense to you?

I don't really know what to do with model and adapter classes. It seems that adapter classes are used just in `gui` but model classes are used in both `gui` and `core`. That's why I put them into special package. Another solution is to put `model` to `core` and `adapter` to `gui` which also makes sense. Which one sounds better to you?

Anyway, it's not going to be a lot of work. Most of the work will be done by Android Studio. These modern IDEs are pretty clever when it comes to moving classes between packages and fixing all their references in other classes.

**Comment by VladislavAlfredov** [comment]
Common Xmpp/Rest interfaces: On second thought, you are right. It is best not to make too many changes at once. And the reorganizing that you propose should be enough for now.

Adapter classes:
 I haven't looked much into them tbh. But since they are used for the gui it sounds reasonable to keep them under : org.dhis2.messenger.gui.adapter.\* , since the model is more to do with app-specific data abstraction, while the adapters are standard on all android apps.

Gcm: Sounds good. Haven't thought of it that way. I somehow thought of it as utils.

Model classes: 
1.You could either put them under their respective branch:
org.dhis2.messenger.xmpp.model.{ConferenceModel, IMMessageModel, RosterModel, IMMesageModel}
org.dhis2.messenger.rest.model.{InterpretationModel, NameAndIdModel, ChatModel}
org.dhis2.messenger.common.model.{ProfileModel, InboxModel}
*\* I am still a bit unsure weather ProfileModel & InboxModel are part of xmpp or rest I will check it tomorrow & let you know **
2. Or under org.dhis2.messenger.model.\* (as they are now)
3. Under org.dhis2.messenger.core.model.*

So far I haven't seen many references to xmmp models from rest models (maybe 1 at most if I remember correctly).
So from one side separating them like (1) comunicates to the reader "these models are for this".
But then again if you want to see all the data models used by the app you have to go trough all the respective .model sub-packages.
All of them work fine if you ask me. It is more of a personal preference question and I'm fine with all of the above mentioned ones :)

Two suggestions that I forgot to mention were: 
Renaming the RESTClient to RestClient, XMPPClient to XmppClient, IMRosterListener to ImRosterListener...etc Using the convention of starting the class/interface with capital leter and not with capital word. (?)
Also RESTSessionStorage to RestSession. WhereStorage is implied by Session. Or maybe only I feel that way (?).
Maybe call gui ui ? 1 less letter and it still comunicates it's purpose clearly

**Comment by livthomas** [comment]
I've made those changes. Try if the application works on your side. If so, we can close this issue.
